//  Raptor - a client API for Terraria
//  Copyright (C) 2013 MarioE
//
//  This program is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with this program.  If not, see <http://www.gnu.org/licenses/>.

namespace Raptor.Api
{
	/// <summary>
	/// Represents the different wall types.
	/// </summary>
	public enum WallTypes : byte
	{
		Stone = 1,
		NaturalDirt,
		NaturalEbonstone,
		Wood,
		GrayBrick,
		RedBrick,
		NaturalBlueBrick,
		NaturalGreenBrick,
		NaturalPinkBrick,
		GoldBrick,
		SilverBrick,
		CopperBrick,
		NaturalHellstoneBrick,
		NaturalObsidianBrick,
		NaturalMud,
		Dirt,
		BlueBrick,
		GreenBrick,
		PinkBrick,
		ObsidianBrick,
		Glass,
		PearlstoneBrick,
		IridescentBrick,
		MudstoneBrick,
		CobaltBrick,
		MythrilBrick,
		Planked,
		NaturalPearlstone,
		CandyCane,
		GreenCandyCane,
		SnowBrick,
		AdamantiteBeam,
		DemoniteBrick,
		SandstoneBrick,
		EbonstoneBrick,
		RedStucco,
		YellowStucco,
		GreenStucco,
		GrayStucco,
		NaturalSnow,
		Ebonwood,
		RichMahogany,
		Pearlwood,
		RainbowBrick,
		TinBrick,
		TungstenBrick,
		PlatinumBrick,
		NaturalAmethyst,
		NaturalTopaz,
		NaturalSapphire,
		NaturalEmerald,
		NaturalRuby,
		NaturalDiamond,
		NaturalCave1,
		NaturalCave2,
		NaturalCave3,
		NaturalCave4,
		NaturalCave5,
		NaturalCave,
		NaturalLeaf,
		NaturalCave6,
		NaturalSpider,
		NaturalGrass,
		NaturalJungle,
		NaturalFlower,
		Grass,
		Jungle,
		Flower,
		NaturalCorruptGrass,
		NaturalHallowedGrass,
		NaturalIce,
		Cactus,
		Cloud,
		GlowingMushroom,
		Bone,
		Slime,
		Flesh,
		LivingWood,
		NaturalObsidianBack,
		NaturalMushroom,
		NaturalCrimsonGrass,
		Disc,
		NaturalCrimstone,
		IceBrick,
		Shadewood,
		NaturalHive,
		NaturalLihzahrdBrick,
		PurpleGlass,
		YellowGlass,
		BlueGlass,
		GreenGlass,
		RedGlass,
		MulticolorGlass,
		NaturalBlueSlab,
		NaturalBlueTiled,
		NaturalPinkSlab,
		NaturalPinkTiled,
		NaturalGreenSlab,
		NaturalGreenTiled,
		BlueSlab,
		BlueTiled,
		PinkSlab,
		PinkTiled,
		GreenSlab,
		GreenTiled,
		WoodenFence,
		MetalFence,
		Hive,
		PalladiumColumn,
		Bubblegum,
		Titanstone,
		LihzahrdBrick
	}
}
